# Generated by Django 5.1.5 on 2025-03-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_artistprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
