# Generated by Django 5.1.5 on 2025-03-06 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_album_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(help_text='Allowed formats: MP3, WAV, OGG, M4A', upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
    ]
