# Generated by Django 5.1.5 on 2025-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_album_description_album_duration_album_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, related_name='followers', to='users.artistprofile'),
        ),
    ]
