# Generated by Django 5.1.5 on 2025-03-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_album_description_about_yourself_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description_about_yourself',
        ),
        migrations.RemoveField(
            model_name='album',
            name='popular_songs_1',
        ),
        migrations.RemoveField(
            model_name='album',
            name='popular_songs_2',
        ),
        migrations.RemoveField(
            model_name='album',
            name='social_links',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='description_about_yourself',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='popular_songs_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='popular_songs_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='social_links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
