# Generated by Django 5.1.5 on 2025-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_album_description_about_yourself_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistprofile',
            options={'ordering': ['-verification_date'], 'verbose_name': 'Artist Profile', 'verbose_name_plural': 'Artist Profiles'},
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='artist_name',
            field=models.CharField(help_text='Enter your artist name.', max_length=100, verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself.', verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='description_about_yourself',
            field=models.TextField(blank=True, help_text='Describe yourself in detail.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='genre',
            field=models.CharField(help_text='Enter your music genre.', max_length=50, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified Status'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='popular_songs_1',
            field=models.CharField(blank=True, help_text='Enter one of your popular songs.', max_length=255, null=True, verbose_name='Popular Song 1'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='popular_songs_2',
            field=models.CharField(blank=True, help_text='Enter another popular song.', max_length=255, null=True, verbose_name='Popular Song 2'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='social_links',
            field=models.URLField(blank=True, help_text='Provide links to your social media profiles.', null=True, verbose_name='Social Links'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='verification_date',
            field=models.DateField(auto_now_add=True, verbose_name='Verification Date'),
        ),
    ]
