# Generated by Django 5.1.5 on 2025-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_artistprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='events_url',
            field=models.URLField(blank=True, null=True, verbose_name='Events URL'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='merchandise_url',
            field=models.URLField(blank=True, null=True, verbose_name='Merchandise URL'),
        ),
    ]
