# Generated by Django 5.1.5 on 2025-03-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_artistprofile_events_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='total_listens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
