# Generated by Django 5.1.5 on 2025-04-02 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='khalti_payment_idx',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='khalti_idx',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('artist_pro', 'Artist Pro')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
