# Generated by Django 5.1.5 on 2025-04-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_premiumad'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='song',
            name='revenue_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('views_count', models.PositiveIntegerField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artistprofile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.song')),
            ],
            options={
                'verbose_name': 'Revenue Record',
                'verbose_name_plural': 'Revenue Records',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
