# Generated by Django 5.1.5 on 2025-04-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_song_play_duration_song_qualified_plays_playhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuerecord',
            old_name='views_count',
            new_name='plays_count',
        ),
    ]
