# Generated by Django 5.1.5 on 2025-04-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_views_count_revenuerecord_plays_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='support_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='support_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='support_qr_codes/'),
        ),
    ]
