# Generated by Django 5.1.5 on 2025-04-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_artistprofile_support_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('artist', 'Verified Artist'), ('premium', 'Premium User')], default='normal', max_length=10),
        ),
    ]
