# Generated by Django 5.1.5 on 2025-04-14 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
