# Generated by Django 5.1.5 on 2025-04-16 03:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_artistprofile_created_at_artistprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='support_qr_code',
            field=models.ImageField(blank=True, help_text='Upload a QR code for fans to support you', null=True, upload_to=users.models.qr_code_upload_path, verbose_name='Support QR Code'),
        ),
    ]
