# Generated by Django 5.1.5 on 2025-05-26 04:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_paymentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_listens', models.PositiveIntegerField()),
                ('requested_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artistprofile')),
            ],
        ),
    ]
