# Generated by Django 5.1.5 on 2025-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='support_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='support_qr/'),
        ),
    ]
